Moved profile operations to it's own class.
Half-Shot/matrix-appservice-twitter pull request #77
Opened 2017-01-20 10:54 UTC by Half-Shot

Rewrote get_profile to use Coroutines

2017-01-20 12:25 UTC, lukebarnard1 requested changes

2017-01-20 12:25 UTC, lukebarnard1 commented on src/twitter/Twitter.js
> +    this._profile = new TwitterProfile(this, config)
semi-colon

2017-01-20 12:25 UTC, lukebarnard1 commented on src/twitter/TwitterProfile.js
> +const Promise  = require('bluebird');
Extra spaces before the '=' on the above two lines

2017-01-20 12:25 UTC, lukebarnard1 commented on src/twitter/TwitterProfile.js
> +Description:${old_profile.description}`);
I'm not _too_ keen on this not being indented properly.  I suggest making each line it's own `...`.

2017-01-20 12:25 UTC, lukebarnard1 commented on src/twitter/TwitterProfile.js
> +Description:${new_profile.description}`);
Similarly to https://github.com/Half-Shot/matrix-appservice-twitter/pull/77/files#r97058123

2017-01-20 12:25 UTC, lukebarnard1 commented on src/twitter/TwitterProfile.js
> +    const intent = this._twitter.get_intent(new_profile.id_str);
I'm not convinced that `new_profile.id_str` is a matrix user ID.

2017-01-20 12:25 UTC, lukebarnard1 commented on src/twitter/TwitterProfile.js
> +    }).catch(error => {
This catch should really be on `client.getAsync(..` above otherwise the log might lie.

2017-01-20 12:25 UTC, lukebarnard1 commented on src/twitter/TwitterProfile.js
> +        error = error[0];
I'm unsure as to why this is necessary

2017-01-22 13:32 UTC, Half-Shot commented on src/twitter/TwitterProfile.js
> +        error = error[0];
Sometimes errors come as an object, and sometimes as an array of objects. Yes, I know -_-

2017-01-23 12:41 UTC, lukebarnard1 approved these changes
LGTM

2017-01-23 12:53 UTC, Half-Shot commented
:tada:

2017-01-23 12:53 UTC, merged